/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semaphoregui;

import Models.Semaphore;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/**
 *
 * @author AlejoMG
 */

class MyIntFilter extends DocumentFilter {
   @Override
   public void insertString(FilterBypass fb, int offset, String string,
         AttributeSet attr) throws BadLocationException {

      Document doc = fb.getDocument();
      StringBuilder sb = new StringBuilder();
      sb.append(doc.getText(0, doc.getLength()));
      sb.insert(offset, string);

      if (test(sb.toString())) {
         super.insertString(fb, offset, string, attr);
      } else {
         // warn the user and don't allow the insert
      }
   }

   private boolean test(String text) {
      try {
         Integer.parseInt(text);
         return true;
      } catch (NumberFormatException e) {
         return false;
      }
   }

   @Override
   public void replace(FilterBypass fb, int offset, int length, String text,
         AttributeSet attrs) throws BadLocationException {

      Document doc = fb.getDocument();
      StringBuilder sb = new StringBuilder();
      sb.append(doc.getText(0, doc.getLength()));
      sb.replace(offset, offset + length, text);

      if (test(sb.toString())) {
         super.replace(fb, offset, length, text, attrs);
      } else {
         // warn the user and don't allow the insert
      }

   }

   @Override
   public void remove(FilterBypass fb, int offset, int length)
         throws BadLocationException {
      Document doc = fb.getDocument();
      StringBuilder sb = new StringBuilder();
      sb.append(doc.getText(0, doc.getLength()));
      sb.delete(offset, offset + length);

      if (test(sb.toString())) {
         super.remove(fb, offset, length);
      } else {
         // warn the user and don't allow the insert
      }

   }
}
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        jTextFieldCarIn.enable(false);
        jTextFieldCarsOut.enable(false);
        PlainDocument bufferDoc = (PlainDocument) jTextFieldBuffer.getDocument();
        bufferDoc.setDocumentFilter(new MyIntFilter());
        PlainDocument inDoc = (PlainDocument) jTextFieldCarIn.getDocument();
        inDoc.setDocumentFilter(new MyIntFilter());
        PlainDocument outDoc = (PlainDocument) jTextFieldCarsOut.getDocument();
        outDoc.setDocumentFilter(new MyIntFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCarsOut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCarsOut = new javax.swing.JButton();
        jButtonCarsIn = new javax.swing.JButton();
        jTextFieldCarIn = new javax.swing.JTextField();
        jTextFieldBuffer = new javax.swing.JTextField();
        jButtonBuffer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelCarsAct = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelParkContainer = new javax.swing.JPanel();
        jPanelParking = new javax.swing.JPanel();
        jPanelQueveContainer = new javax.swing.JPanel();
        jPanelQueve = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(668, 309));

        jLabel1.setText("Carros en espera");

        jButtonCarsOut.setText("Aceptar");
        jButtonCarsOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarsOutActionPerformed(evt);
            }
        });

        jButtonCarsIn.setText("Aceptar");
        jButtonCarsIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarsInActionPerformed(evt);
            }
        });

        jButtonBuffer.setText("Aceptar");
        jButtonBuffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBufferActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Espacios libres:");

        jLabelCarsAct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCarsAct.setText("0");

        jLabel3.setText("Sacar carros");

        jLabel4.setText("Ingresar carros");

        jLabel5.setText("Tamaño de buffer");

        javax.swing.GroupLayout jPanelParkingLayout = new javax.swing.GroupLayout(jPanelParking);
        jPanelParking.setLayout(jPanelParkingLayout);
        jPanelParkingLayout.setHorizontalGroup(
            jPanelParkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelParkingLayout.setVerticalGroup(
            jPanelParkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelParkContainerLayout = new javax.swing.GroupLayout(jPanelParkContainer);
        jPanelParkContainer.setLayout(jPanelParkContainerLayout);
        jPanelParkContainerLayout.setHorizontalGroup(
            jPanelParkContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelParkContainerLayout.setVerticalGroup(
            jPanelParkContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelQueveLayout = new javax.swing.GroupLayout(jPanelQueve);
        jPanelQueve.setLayout(jPanelQueveLayout);
        jPanelQueveLayout.setHorizontalGroup(
            jPanelQueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelQueveLayout.setVerticalGroup(
            jPanelQueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelQueveContainerLayout = new javax.swing.GroupLayout(jPanelQueveContainer);
        jPanelQueveContainer.setLayout(jPanelQueveContainerLayout);
        jPanelQueveContainerLayout.setHorizontalGroup(
            jPanelQueveContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelQueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelQueveContainerLayout.setVerticalGroup(
            jPanelQueveContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelQueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCarIn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCarsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCarsOut, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCarsOut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addComponent(jPanelQueveContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCarsAct)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelParkContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCarsAct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldBuffer)
                            .addComponent(jButtonBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCarIn)
                            .addComponent(jButtonCarsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCarsOut)
                            .addComponent(jButtonCarsOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelQueveContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelParkContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void representParking(int used) {
        jPanelParkContainer.removeAll();
        jPanelParkContainer.repaint();
        Rectangle tamaño = jPanelParking.getBounds();
        jPanelParking = new javax.swing.JPanel();
        for (int i = 0; i < used; i++) {
            int j = i / 6;
            javax.swing.JLabel jCar = new javax.swing.JLabel("");
            jCar.setIcon(img);
            jCar.setBounds(290 - (110 * j), 280 - (50 * (i % 6)), 105, 50);
            jPanelParking.setLayout(null);
            jPanelParkContainer.add(jPanelParking, JLayeredPane.DEFAULT_LAYER);
            jPanelParking.add(jCar);
        }
        jPanelParking.setBackground(new java.awt.Color(204, 204, 204));
        jPanelParking.setVisible(true);
        jPanelParking.setBounds(tamaño);
        jPanelParking.setEnabled(false);
    }
    
    private void representQueve(int used) {
        jPanelQueveContainer.removeAll();
        jPanelQueveContainer.repaint();
        Rectangle tamaño = jPanelQueve.getBounds();
        jPanelQueve = new javax.swing.JPanel();
        for (int i = 0; i < used; i++) {
            int j = i / 2;
            javax.swing.JLabel jCar = new javax.swing.JLabel("");
            jCar.setIcon(img);
            jCar.setBounds(175- (110 * j), 65-(50 * (i % 2)), 105, 50);
            jPanelQueve.setLayout(null);
            jPanelQueveContainer.add(jPanelQueve);
            jPanelQueve.add(jCar);
        }
        jPanelQueve.setBackground(new java.awt.Color(204, 204, 204));
        jPanelQueve.setVisible(true);
        jPanelQueve.setBounds(tamaño);
        jPanelQueve.setEnabled(false);
    }

    private void jButtonBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBufferActionPerformed
        int buffer = Integer.parseInt(jTextFieldBuffer.getText());
        if (sem == null) {
            sem = new Semaphore(buffer);
            jTextFieldCarIn.enable(true);
            jTextFieldCarsOut.enable(true);
        } else {
            sem.setBuffer(buffer);
        }
        jLabelCarsAct.setText(String.valueOf(sem.getBuffer()));
        representParking(sem.getUsed());
        representQueve(sem.getInQueue());
        jTextFieldBuffer.setText("0");
    }//GEN-LAST:event_jButtonBufferActionPerformed

    private void jButtonCarsInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarsInActionPerformed
        int use = Integer.parseInt(jTextFieldCarIn.getText());
        int used = sem.useBuffer(use);
        jLabelCarsAct.setText(String.valueOf(sem.getBuffer() - used));
        representParking(used);
        representQueve(sem.getInQueue());
        jTextFieldCarIn.setText("0");
    }//GEN-LAST:event_jButtonCarsInActionPerformed

    private void jButtonCarsOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarsOutActionPerformed
        int free = Integer.parseInt(jTextFieldCarsOut.getText());
        int used = sem.freeBuffer(free);
        jLabelCarsAct.setText(String.valueOf(sem.getBuffer() - used));
        representParking(used);
        representQueve(sem.getInQueue());
        jTextFieldCarsOut.setText("0");
    }//GEN-LAST:event_jButtonCarsOutActionPerformed

    Semaphore sem;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuffer;
    private javax.swing.JButton jButtonCarsIn;
    private javax.swing.JButton jButtonCarsOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCarsAct;
    private javax.swing.JPanel jPanelParkContainer;
    private javax.swing.JPanel jPanelParking;
    private javax.swing.JPanel jPanelQueve;
    private javax.swing.JPanel jPanelQueveContainer;
    private javax.swing.JTextField jTextFieldBuffer;
    private javax.swing.JTextField jTextFieldCarIn;
    private javax.swing.JTextField jTextFieldCarsOut;
    // End of variables declaration//GEN-END:variables
    private ImageIcon img = new ImageIcon(getClass().getResource("/assets/car.png"));
}
