/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semaphoregui;

import Models.Semaphore;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author AlejoMG
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        jTextFieldCarIn.enable(false);
        jTextFieldCarsOut.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCarsOut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCarsOut = new javax.swing.JButton();
        jButtonCarsIn = new javax.swing.JButton();
        jTextFieldCarIn = new javax.swing.JTextField();
        jTextFieldBuffer = new javax.swing.JTextField();
        jButtonBuffer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPaneWait = new javax.swing.JScrollPane();
        jLabelCarsAct = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelPark = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(668, 309));

        jLabel1.setText("Carros en espera");

        jButtonCarsOut.setText("Aceptar");
        jButtonCarsOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarsOutActionPerformed(evt);
            }
        });

        jButtonCarsIn.setText("Aceptar");
        jButtonCarsIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarsInActionPerformed(evt);
            }
        });

        jButtonBuffer.setText("Aceptar");
        jButtonBuffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBufferActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Espacios libres:");

        jScrollPaneWait.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCarsAct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCarsAct.setText("0");

        jLabel3.setText("Sacar carros");

        jLabel4.setText("Ingresar carros");

        jLabel5.setText("Tamaño de buffer");

        jPanelPark.setBackground(new java.awt.Color(255, 255, 255));

        jInternalFrame1.setTitle("Parqueadero");
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelParkLayout = new javax.swing.GroupLayout(jPanelPark);
        jPanelPark.setLayout(jPanelParkLayout);
        jPanelParkLayout.setHorizontalGroup(
            jPanelParkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        jPanelParkLayout.setVerticalGroup(
            jPanelParkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCarIn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCarsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCarsOut, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCarsOut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneWait, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCarsAct)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCarsAct))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldBuffer)
                            .addComponent(jButtonBuffer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCarIn)
                            .addComponent(jButtonCarsIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCarsOut)
                            .addComponent(jButtonCarsOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneWait, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void representParking(int used) {
        jPanelPark.removeAll();
        jPanelPark.repaint();
        Rectangle tamaño = jInternalFrame1.getBounds();
        jInternalFrame1 = new javax.swing.JInternalFrame("Parqueadero", true);
        for (int i = 0; i < used; i++) {
            int j = i / 4;
            javax.swing.JLabel jCar = new javax.swing.JLabel("");
            jCar.setIcon(img);
            jCar.setBounds(225 - (110 * j), 175 - (50 * (i % 4)), 105, 50);
            jInternalFrame1.setLayout(null);
            jPanelPark.add(jInternalFrame1, JLayeredPane.DEFAULT_LAYER);
            jInternalFrame1.add(jCar);
        }
        jInternalFrame1.setVisible(true);
        jInternalFrame1.setBounds(tamaño);
        jInternalFrame1.setEnabled(false);
    }

    private void jButtonBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBufferActionPerformed
        int buffer = Integer.parseInt(jTextFieldBuffer.getText());
        if (sem == null) {
            sem = new Semaphore(buffer);
            jTextFieldCarIn.enable(true);
            jTextFieldCarsOut.enable(true);
        } else {
            sem.setBuffer(buffer);
        }
        jLabelCarsAct.setText(String.valueOf(sem.getBuffer()));
    }//GEN-LAST:event_jButtonBufferActionPerformed

    private void jButtonCarsInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarsInActionPerformed
        int use = Integer.parseInt(jTextFieldCarIn.getText());
        int used = sem.useBuffer(use);
        jLabelCarsAct.setText(String.valueOf(sem.getBuffer() - used));
        representParking(used);
    }//GEN-LAST:event_jButtonCarsInActionPerformed

    private void jButtonCarsOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarsOutActionPerformed
        int free = Integer.parseInt(jTextFieldCarsOut.getText());
        int used = sem.freeBuffer(free);
        jLabelCarsAct.setText(String.valueOf(sem.getBuffer() - used));
        System.out.println(used);
    }//GEN-LAST:event_jButtonCarsOutActionPerformed

    Semaphore sem;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuffer;
    private javax.swing.JButton jButtonCarsIn;
    private javax.swing.JButton jButtonCarsOut;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCarsAct;
    private javax.swing.JPanel jPanelPark;
    private javax.swing.JScrollPane jScrollPaneWait;
    private javax.swing.JTextField jTextFieldBuffer;
    private javax.swing.JTextField jTextFieldCarIn;
    private javax.swing.JTextField jTextFieldCarsOut;
    // End of variables declaration//GEN-END:variables
    private ImageIcon img = new ImageIcon(getClass().getResource("/assets/car.png"));
}
